apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: &name harbor-token-ca
spec:
  isCA: true
  commonName: *name
  secretName: *name
  privateKey:
    algorithm: RSA
    size: 2048
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
    group: cert-manager.io
