apiVersion: v1
kind: Secret
metadata:
  name: homelab-registry-secret
type: Opaque
stringData:
  config.json: |
    {
    	"auths": {
    		"https://index.docker.io/v1/": {
    			"auth": "<path:homelab/data/secrets/dockerhub#auth | base64encode>"
    		}
    	}
    }
