apiVersion: v1
kind: Secret
metadata:
  name: homelab-registry-secret
type: Opaque
stringData:
  config.json: |
    {
    	"auths": {
    		"harbor.homelab.linhng98.com": {
    			"auth": "<path:homelab/data/secrets/harbor#auth | base64encode>"
    		}
    	}
    }
