apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: homelab-registry-secret
  namespace: github-action
spec:
  encryptedData:
    config.json: AgAnnrwuKuhpNtTT4a+bTA69iAzdXWeOEt3zd579UmdwzL1mU6vOVgKAMMLjVKPK1rWNsE81DVYfDc2hwMd9ncnnQr3dpvEzPqFLT3lLhiF8AS/hrXeAOgI8lGGSWWeZMx209kKgcOZ8dOlG1lErbbWI38uHOn6XPSTmZRw84mLYx3GfVaf9QyKXBrKjJG2OpU2ZUlcSWX41kqsV11mCsItIJATFTBGi5zZtbrXsqEgKziFsvMLbNStVIc8S3gbYm7WX20e775B4xE+uiWx/s92OgoOgDlLOWTTLG24r3SDxHfEDA9/zRPwEynAvGPKspr2rnb6KBLSgljZUXpiWY5MJhspEk4nbJ9wnat3u/bINZQ9hIuLgVm3UcCIrk7L04z2v3Lqp9sU+bM2NdhI25reAg1euIWfrW1Y21nhlBQOiqU/RAj20sMMfWvxkvyjlIG/EuuPcCGHzDyLZyE6qh3tqwap2TJn9E/4pVbIbweXZDpa1xK0YzV8eCzsMEeCcvhygh3m/0fZm7CblTFU/nbmDVSCpnoLl5LzdVvTvJCPZ6t/dVYGvFwbvX3jeN5Xr+VQe5bJEsDPef9uG+A+FQrgTQEGOpkGcDgmWdjZ0Ic2Q150dbyUwYeVHgERUEgyCpJTVM6fAamckTxixR3n+XrZhOKe2SRQClWe0QE2TGcY7TDlvlcuqjhRNECGflrG7tRoF+L8+uYJ5UFxt8zM3AuBL3YznvTRXd30e7icI7ZYPl/yw0eVjFDvsqr1gTsOwAU2wNg5LEsxZomDmYc3YqycySoKZLrCyw03TQGFnCn5NufdGcHXEJ266OP/TAMrsuoGnU8gg+8yzo5HDT8XOkPhVONEGlczgFMyznu6S
