apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
type: Opaque
stringData:
  credentials: |
    [default]
    aws_access_key_id=<path:homelab/data/aws-credentials/kaniko-context#aws_access_key_id>
    aws_secret_access_key=<path:homelab/data/aws-credentials/kaniko-context#aws_secret_access_key>
