apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: github-action-sa
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: github-action-sa
subjects:
- kind: ServiceAccount
  name: github-action-actions-runner-controller
  apiGroup: ""
- kind: ServiceAccount
  name: default
  apiGroup: ""
roleRef:
  kind: Role
  name: github-action-sa
  apiGroup: rbac.authorization.k8s.io
