version: '3.8'
services:
  apache2:
    image: httpd:2.4.54-alpine
    volumes:
      - ./data/ubuntu:/usr/local/apache2/htdocs/pxe/ubuntu
      - ./data/autoinstall.d:/usr/local/apache2/htdocs/pxe/autoinstall.d
    network_mode: host
  dnsmasq:
    build:
      dockerfile: Dockerfile.dnsmasq
      context: ./
    network_mode: host
    cap_add:
      - NET_ADMIN
    volumes:
      - ./data/configs/dnsmasq.conf:/etc/dnsmasq.conf
      - ./data/configs/grub.cfg:/srv/tftp/grub/grub.cfg
      - ./data/ubuntu:/srv/tftp/ubuntu
