---
deploychart:
  replicaCount: 1
  image:
    repository: snowdreamtech/frpc:0.44.0
  pullPolicy: IfNotPresent

  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

  fullnameOverride: frpc-client

  sealedSecrets:
    enabled: true
    encryptedData:
      mapFile:
        - mountPath: /etc/frp
          name: frpc-client
          files:
            - name: frpc.ini
              value: AgCiDv1p4t3/rMkoMQgfXqrSTrOCNPlDUEpmUJfQZEMgEntDwc3w9GIrNb468GCGrGgieebZzX+TkEul4GlvfUGEXogrB1dqycFyjGe1TU7WW5lbUv1MowmUJe3D0PiucaSSp1YTppYrJ+ZuepNkbaIr+XqQ9ij6JJDmTyZ7p20sy56JCZS0TdGt/aoW6w9EmElEN39vpcaj1+V87V62TMxzdgkTAQYnCHxxChZWUjD0TnH2P1Kqv8zoADo0giEVRp7vAHM35fb/49rtU2/y1nmGHPk/jvo3qcOhQrZYYy26l7204w3DLeNj6xg9SBsLHpRl3H2I9J38OOitYt1xuxDxWEvJUCQh1CVvAeZMdVSpr7FRFPCwKllPbgMsKyqiX7Bkv/lN/+2f15WW2DM/0kdzkX1I/Xg+kalA6rGVC88OX+hp42N3wRUcn/1vAkYE4CvXpGd9kbsymxa+64eA0o101XcReSYFxFIynSGYa78EhK9pDy5vqEd54o06Ag8gnAj+YhOgISZPaUetd51DDVamhJS5rsJB4bvl/vFJLKT3eA/IY3WIG4MOcbZRYkUya0H2T03oKJ7SJu25E39RXKiVGrIuc34RmCWdrLa7FTFX6mbnfvdbM2gXn1xAvVU4jqB5EPmDgYflyw27qFRYei/kK+mOU3OeIvFjx1N3IDqrpmni9MO/9f65JgFzADp/7cT/MFF4J3V8Bw8AL+kaGa/VL3YKLNZ9jdfadLzgabczpmPj8Zd02xTBwGgfs91Yocv0uPXapohQLA91EvxC8dxa6y7EIiP34pZxz5fSoOrBOxAHBqbyCM7nE05ByljPudRgSawZk1fXBXIdML248h8gJ4cymqHI2eAE7BxsXIsqZhGh2nN3o6yRNqMZTQzHoLPlke6sVmW9ULIvUP9e2aTrmM+q/Vew6ZTE18/eXeNjL0QwKbUmcafO/tOSaeJjAIpa4m19XTTrN7bspDfguUlGL9gOlV22WRHRkOq+6IIvPxHvsgBokDi7g7TfAUz153PWQ8XRiXtUq6vGLebJf47dLNFfg+tqF7wURLCF7HtcWF6V+FmCIVXH3GilzAIfNhYxiwpXzp/dYSsvGIhMm2jgldxhNQ7IwBzk1iL2PpxqgmxU/Z3EyGfk6cMgquRrHs5vTj8/nDRfcbupoCm9WR84up8QJRqJoOD34fCpbOGplrI+SxxbU11Ic63UlcDtmU2oFuf7v6lGt/OmkxEnBdTss8MptWP1Cl/CPq5pYvWFGfpgTsdAjmwL0GJ+gRwhEDBiPRrEEVF+F/DcEBdNr6X4a0UGINnmKjnzH2F3FvkchIykg3jVKxlM4oWrtg==
              path: frpc.ini
