---
deploychart:
  replicaCount: 1
  image:
    repository: snowdreamtech/frpc:0.44.0
  pullPolicy: IfNotPresent

  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

  fullnameOverride: frpc-client

  sealedSecrets:
    enabled: true
    encryptedData:
      mapFile:
        - mountPath: /etc/frp
          name: frpc-client
          files:
            - name: frpc.ini
              value: AgA234wmBg+BzTN6knmvKw4IqytzY0nyROCGVWLQk8JBkubWkr4dYiM2LImyCN2IeikUhq75PpWcQwmkAeuZVaxa0AmqGenykd7Y+KAEdJ7onUc34Y2ffhwOlzefUyI7ThWDHim+6qjzt3qF4ea71jAVAp//KGP4IuOVte48nsbw6gsjgl1F+oqDoeyyrqSc4IGPju4gT4iPqNJF68tiTXY+dXyCLCoZdhfRWkPqw3HJBs0n7ZNsG1LaHliBeJ791SeQBjWzvay5745ReKYS+Tx5ELKqQ3yTy5RCBj+J3CEmrFwaQDt2tKSjhAHyerltTBoZKdFI0BwV2NPnpxmptvxOP5/cHzOC6Pcf3yVNislHkA/jSK/P6SNzPgf3I0EUbVVPyEvdWPmOnUvRoKXwNRoTM/ULBsbL9Bl9cTd0J8LLFIuE/ZIj6p7r8VhjoMXPyYkZcDMo+8Sp2NWJX56vAHricU9we8PdV0syIrH3ceNNH+MFscR+zb6Tjtkwu96Ze0uMEQ/4v4YaKiuAkhPg12zt3JMdjLzwaqy31gjzGf0ZKHuAd+4g1zL5a7cxzNzRNs9vUfEu+W2mgyu7zivfvzbxKP49kD4CU6lik87UcYTMVSPwCmWGLIi5PUkHLCZ+uSnAU064pTbHKk+nSUsmjYsi/MarXm22vVlGCsf/J6wrr45Vv0O/Clrc0Y/smha8jBrU8xEc1IH4e4qM+f3I8GRO1VNFr+9ulhdraNVwKMzBA8EZp2UJBa7Kr4ZRTHNUEpY5MoHkGSu7RjCDu4T9iKgSCkCIybqW0WHhr1U1ocU/tzC4fzq0TL59iRbYJJMnH4Aj5U+y7s3iKSfh3cGlJFbcQWrGIWZ637bTNh8q4DwpnZxDulxineY0irHhU2Z8xgvj5Z0vMUXWw1ylPw6YmIGvFz3VDUThiXUjG5mBCJjHGEkQfgnmP3Kwx7hZ01ZimubjdujJMGj88d6X7H1XKR4tE0W+gWrF5QBKnle0dxs+Bvpqt+TN0+IaFMF5q4O+jJavVzdfPW1VF/yleXBz4yGsUF33Ynf+OYoTghCDxy5bn4D2hA3C7xv8nR46KZ5AA7heI5Bomy2s1OUgNYv5OX4DDVJomP4kldBHjrd0WCERCaNrAP2vPZcnFlupsK4Hw/jVE7gZ8QEdWH8HnCISn1ymBZUs92b73nAKfEzNrFdpJUDAAvB3CO2TGhcT1NGsaE8=
              path: /
