---
deploychart:
  replicaCount: 1
  image:
    repository: snowdreamtech/frpc:0.44.0
  pullPolicy: IfNotPresent

  strategy:
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1

  fullnameOverride: frpc-client

  sealedSecrets:
    enabled: true
    encryptedData:
      mapFile:
        - mountPath: /etc/frp
          name: frpc-client
          files:
            - name: frpc.ini
              value: AgAcOgto4h8VKQzbxSe+ycSmhmr5A9Avctrawi/FmhqrdWupr+MRV7RcEV/mFKDAoCwfjFpXJsg9HnmwUKi01W2/YHqrWX6QBLNpi0MuYHaAjurIfM4ytYWBz7GmRfVEcYUP/8IR5GXFJugLbkVf3xFAbUUKXF39gKqMlvd2PoV17gkp9sURqxXCZrrsdrvgpK2JJrTzmfv3Z0gnVpMeRivQ4CRAzhBWNkzecYdW5Ee+IEO8LeB3jiQPSbu026RzY1Guowe3cV0IGlajm9UYglOsI7fa4o8EYNXfQKJnXg4Urs+NyWeyafiUC9cVg4K5DR7k4boRP0q2SRz4U4eZBEADJtEvy2tD+3AjpqfCjDFPXJiuEASgJhtMKjW3swK/IClBngLYXWCEe2qLW6ar5hMFe7Ehmm+uVhhTvaY7GToOy3lDNZwJwfDUI+beSBC7MV6F8q+UvUNbDU0DVOr/BmnWIub7qyx1QUBmCqPt5GX90Vsv9PmZPK2d7djzcCltquDpB/k7qSkc+C9HusA4HEUNbpu9ByjWw9hCl8De8msiLoWxD715VxPdNEsf/9+UYaCc5W0jWG0pb/+RW1GJ7pr+slhT2M2lklmdP5Bm9yv7swJPLhX6U21Qbnt75C085i7MA3mEwae6iZKvhN+HNKUaqCwOj/TufZT5BGNVwB9TbmJN1YIVIFxhDuW/HekWBtLyvaO7TtcwiPXw8fj4JC6eAVDKpA4s+eox7+0WBtX+uTsjl2CYhEogpbP9qVr+VexP0ZbzZjc4YGztVU57mYjIdqeTChLJI1POiqCLH2gwDBtDGvXK5p8VT1wZ3EZYeX0EQpdHu2n5pCP98n52SNzCyNOoJcWrwk2gsWrn7hYeP7uixykIDmsuavOy2bYKTQgL2CvTGYEsKN00Itf5b1hviMvKaZ5NpMGM8qGxI55fTYo10s/k7bD2Qw8u3fmeASZ2BidrN3HvwfRmK1WJccS1Wwg1G50u00LGCVYFx8cfiDKnr4fA2vjTVeo52graxzaEsqY1UQGXtsehLo6S0cIQ8psBZX/mNJrLi77wAb+KGzriAPDRG0+7l/jLT8rNocXyEEIXyf73qHo+mxj78bZ9cEXcKA8tvzz84LcJro70Wr6suZ1uYQgVOvBOX+2K/tl958D1Oe0XZx8yoXL4zmEmPPnCdjwWqxxhSHPkbdFzsRCDTrZu0TgA+0uMs+CjfciZk7mZU1SAZcf32W5LFz1yS/WOx30ZB5qtygS8mUHNlmsfOJl7mOJmk4MXhFQGItgZhlRhXxtuIiYzaxr5e1l14Q6elnk3itkkzV3EzD+bKlVemyNv1GeZq9IGU4pz6ZqGjQxCJAPQ+OPHtlaaY/yBU53XncxBoB5oahUfhuLZ6UBOB9HDqurugpEZpA0+nP1wYT6s9zYkiGK4dP1bQL6qjcRf10kabfY/qdko/zA38t9zdx4gSN19B0+d2gxtvabkBVHEFrn1uFooTHkjjbj2/WFCPns4sE5ONOP+1CKS07isDTf8sT1U554PA+FNfMzZnukwayY6grTxppt+hro7/wdfhKPvme7PFR+rQXlY7cOKIeNkWjxR12Chd+0UyXWKyCX6ZMM+PiWH7nwfgWaxcp5Sd/IBTESGBpzXygKgzvG3rbeKOiUk+OZx0BA/bRuLLMjhu/0W/QxqATxin2QJ8ls+8Y8je/O1H3qNyZRKGqeP0UIurS/HLiA8RZYLjuPU6yzBQV7+r1jonnEl8MTtbgou2cmCNN2wZ1b8OkN0EhAZVyo=
              path: frpc.ini
