---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        exclude: ^.*templates\/.*\.(yaml|yml)
        args: [--allow-multiple-documents]
      - id: check-added-large-files
        args: [--maxkb=2000]
      - id: check-merge-conflict
      - id: check-xml
      - id: check-toml
      - id: pretty-format-json
        args: [--autofix]
      - id: check-json
      - id: check-executables-have-shebangs

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.27.1
    hooks:
      - id: yamllint
        exclude: ^.*templates\/.*\.(yaml|yml)

  - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
    rev: 0.2.2
    hooks:
      - id: yamlfmt
        args: [--mapping, '2', --sequence, '4', --offset, '2']
        exclude: ^.*templates\/.*\.(yaml|yml)

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.74.1
    hooks:
      - id: terraform_fmt
      - id: terragrunt_fmt

  - repo: https://github.com/ambv/black
    rev: 22.6.0
    hooks:
      - id: black

  - repo: https://github.com/google/go-jsonnet
    rev: v0.18.0
    hooks:
      - id: jsonnet-format
      - id: jsonnet-lint

  - repo: https://github.com/trufflesecurity/trufflehog.git
    rev: v3.41.1
    hooks:
      - id: trufflehog
        name: TruffleHog
        description: Detect secrets in your data.
        entry: bash -c 'trufflehog git file://. --since-commit HEAD --only-verified --fail --no-update'
        language: system
        stages: [commit, push]
