temporal:
  server:
    enabled: true
    config:
      persistence:
        defaultStore: default
        default:
          driver: "cassandra"
  admintools:
    enabled: true
  web:
    enabled: true
    replicaCount: 1
    ingress:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      hosts:
        - &host temporal.homelab.linhng98.com
      tls:
        - secretName: temporal-tls
          hosts:
            - *host
  elasticsearch:
    enabled: false
    external: true
    host: "elastic.homelab.linhng98.com"
    port: "443"
    scheme: "https"
    logLevel: "error"
    username: "elastic"
    password: "<path:homelab/data/secrets/elastic#password>"
  prometheus:
    enabled: false
  grafana:
    enabled: false
  cassandra:
    enabled: true
    persistence:
      enabled: true
      size: 5Gi
    image:
      repo: cassandra
      tag: 3.11.3
      pullPolicy: IfNotPresent
    config:
      cluster_size: 3
      ports:
        cql: 9042
      num_tokens: 4
      max_heap_size: 512M
      heap_new_size: 128M
      seed_size: 0
    service:
      type: ClusterIP
