---
apiVersion: v1
kind: Pod
metadata:
  name: kaniko-<BUILD_ID>
spec:
  containers:
    - name: kaniko
      image: gcr.io/kaniko-project/executor:latest
      args:
        - "--dockerfile=<DOCKERFILE>"
        - "--context=<CONTEXT>"
        - "--destination=<IMAGE_TAG>"
        - "--use-new-run"
        - "--snapshot-mode=redo"
        - "--cache=true"
        - "--cache-dir=/cache"
      volumeMounts:
        - name: aws-secret
          mountPath: /root/.aws/
        - name: homelab-registry-secret
          mountPath: /kaniko/.docker/
        - name: kaniko-cache
          mountPath: /cache
      #env:
      #  - name: AWS_REGION
      #    value: ap-southeast-1
  restartPolicy: Never
  volumes:
    - name: aws-secret
      secret:
        secretName: aws-secret
    - name: homelab-registry-secret
      secret:
        secretName: homelab-registry-secret
    - name: kaniko-cache
      persistentVolumeClaim:
        claimName: kaniko-cache
        readOnly: false
