---
nats:
  nats:
    image:
      repository: nats
      tag: 2.9.8-alpine
      pullPolicy: IfNotPresent

    jetstream:
      enabled: true

      memStorage:
        enabled: true
        size: 1Gi

      fileStorage:
        enabled: true
        storageDirectory: /data
        size: 5Gi

  cluster:
    enabled: true
    replicas: 3

  natsbox:
    enabled: true

  exporter:
    enabled: true
    serviceMonitor:
      enabled: true
