---
cp-helm-charts:
  cp-zookeeper:
    enabled: true
    image: confluentinc/cp-zookeeper
    imageTag: 7.1.0
    servers: 3
    heapOptions: -Xms512M -Xmx512M
    persistence:
      enabled: true
      ## The size of the PersistentVolume to allocate to each Zookeeper Pod in the StatefulSet. For
      ## production servers this number should likely be much larger.
      ##
      ## Size for Data dir, where ZooKeeper will store the in-memory database snapshots.
      dataDirSize: 5Gi
      ## Size for data log dir, which is a dedicated log device to be used, and helps avoid competition between logging and snaphots.
      dataLogDirSize: 5Gi

    resources: {}
    #  limits:
    #   cpu: 100m
    #   memory: 128Mi
    #  requests:
    #   cpu: 100m
    #   memory: 128Mi

  cp-kafka:
    enabled: true
    image: confluentinc/cp-enterprise-kafka
    imageTag: 7.1.0
    brokers: 3
    heapOptions: -Xms512M -Xmx512M

    configurationOverrides:
      offsets.topic.replication.factor: '2'
      default.replication.factor: 2
      min.insync.replicas: 2
      auto.create.topics.enable: true

    persistence:
      enabled: true
      size: 1Gi
      disksPerBroker: 1
    resources: {}
    ## If you do want to specify resources, uncomment the following lines, adjust them as necessary,
    ## and remove the curly braces after 'resources:'
    #  limits:
    #   cpu: 100m
    #   memory: 128Mi
    #  requests:
    #   cpu: 100m
    #   memory: 128Mi
    securityContext:
      runAsUser: 0


  cp-schema-registry:
    enabled: false

  cp-kafka-rest:
    enabled: false

  cp-kafka-connect:
    enabled: false

  cp-ksql-server:
    enabled: false

  cp-control-center:
    enabled: false

kafka-ui:
  replicaCount: 1
  env:
    - name: KAFKA_CLUSTERS_0_NAME
      value: confluent-kafka
    - name: KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS
      value: confluent-kafka-cp-kafka:9092
  ingress:
    enabled: true
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/auth-type: basic
      nginx.ingress.kubernetes.io/auth-secret: kafka-ui-basic-auth
    ingressClassName: nginx
    path: /
    host: kafka.homelab.linhng98.com
    tls:
      enabled: true
      secretName: kafka-ui-tls
