apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel-collector
spec:
  mode: daemonset
  config: |
    receivers:
      zipkin:
      jaeger:
        protocols:
          grpc:
      otlp/http:
        protocols:
          http:
      otlp/grpc:
        protocols:
          grpc:
    processors:
      tail_sampling:
        decision_wait: 20s
        policies:
          - name: high-latency
            type: latency
            latency:
              threshold_ms: 500
          - name: error
            type: status_code
            status_code:
              status_codes:
                - ERROR
    exporters:
      otlphttp:
        endpoint: http://tempo-distributor.tempo:4318
      loadbalancing:
        routing_key: "traceID"
        protocol:
          otlp:
            timeout: 1s
            tls:
              insecure: true
        resolver:
          dns:
            hostname: otel-collector-collector-headless.otel-collector
            port: 4317

    service:
      pipelines:
        traces/loadbalancer:
          receivers: [otlp/http]
          processors: []
          exporters: [loadbalancing]
        traces/backend:
          receivers: [otlp/grpc]
          processors: [tail_sampling]
          exporters: [otlphttp]
