apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel-collector
spec:
  mode: daemonset
  config: |
    receivers:
      zipkin:
      jaeger:
        protocols:
          grpc:
      otlp:
        protocols:
          grpc:
          http:

    processors:

    exporters:
      otlphttp:
        endpoint: "http://tempo-gateway.tempo/otlp/v1/traces"

    service:
      pipelines:
        traces:
          receivers: [otlp, jaeger, zipkin]
          processors: []
          exporters: [otlphttp]
