# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cp-zookeeper
spec:
  endpoints:
  - port: metrics
  selector:
    matchLabels:
      app: cp-zookeeper
