apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: kafka-ui-basic-auth
  namespace: confluent-kafka
spec:
  encryptedData:
    auth: AgC7M9SWgfq9qFoeE9tBji5t5BzTxvICJwsGoIOhZ26fgy2ughhyRz+SVNchZN/4a/HF1Bskg9+95DM2u0t5u9xBI0LrsPW9CaZsZM54LDOBDH3MU35OpISJQpQ+PjgACQzl7OjgoBa2UTP1vwisqsDPmpIQYD3wqMTesWEalk/R7TlV9xPLWL14IG0ci3n1kOfM0oRRp+RMnaiREtPjw6IDn8x3fsZNRHR9DUlG6GgAmq9/q1h09Beae7W5jJKPeBx9EJTquDfk3xaaxacDYgsoGHM4hb5NitRHaYxR15l4qOOkZ7Ro3k+2bmXMeRV7chTr3+9G/WfosKYpFnncXo1KLze6f30dfUrsh07LIO4qmrwRuAN/l36/nBljyO27Dqbj37Vb3U7imxa5FuvZibKCgNa+s9R7lW2jH4C/I6Nnr4kfMtPGLHqOUAxdUdzI/CqNwVzlnPHQ2k69ojuzuELvP697qM2fARDG30IGJmCMHz8tLc3Eqt3+8bTQYADdxCNeuRIjfZItefVNl+o8Y1xTHhxLbKpJ1lXkOHalQbJGVeY1inAr2NXJrHByiSoQ3pkzh52wxpS4xRLVVnfRwMd0Rj5oAvb/EueG85oGZ+EwnHB+RH3bpkCuGTKD8+X0jtAV+NMd3CItpIpwl5WXJE9al1yRXO3vE8Q+KdJbyzEZ+GXXNou9na+6Pqol5PgXw+Gt9GZCUJ5C+6W0Xnrx6tydfKks5Z0XqSFlq502VSdPihJTIc51p1TfdrNw
