---
  - name: Create daily upgrade script
    ansible.builtin.file:
      path: &cron /etc/cron.daily/upgrade
      state: touch
      mode: '0755'
  - name: Script to upgrade
    ansible.builtin.copy:
      dest: *cron
      content: |
        #!/bin/bash
        apt-get update -y > /var/log/daily-update.log
        apt-get upgrade -y > /var/log/daily-upgrade.log
        apt-get autoclean
        if test -f "/var/run/reboot-required"; then
          reboot
        fi
