---
apiVersion: v2
name: elastic-cluster
version: 0.0.0
dependencies:
  - name: elasticsearch
    version: 7.17.3
    repository: https://helm.elastic.co
  - name: kibana
    version: 7.17.3
    repository: https://helm.elastic.co
