apiVersion: batch/v1
kind: CronJob
metadata:
  name: renovate
spec:
  schedule: 0 * * * *
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: renovate
              image: renovate/renovate:34.24.0
              envFrom:
                - secretRef:
                    name: renovate-env
          restartPolicy: Never
