tempo-distributed:
  reportingEnabled: false
  global_overrides:
    metrics_generator_processors:
      - service-graphs
      - span-metrics
  global:
    dnsService: rke2-coredns-rke2-coredns
    dnsNamespace: kube-system
    clusterDomain: cluster.local
  ingester:
    replicas: 3
    persistence:
      enabled: true
      size: 2Gi
  metricsGenerator:
    enabled: true
    replicas: 1
    config:
      storage:
        remote_write:
          - url: http://mimir-nginx.mimir/api/v1/push
            headers:
              X-Scope-OrgID: homelab
  distributor:
    replicas: 3
  compactor:
    replicas: 1
  querier:
    replicas: 1
  queryFrontend:
    replicas: 1
  search:
    enabled: true
  multitenancyEnabled: false
  traces:
    otlp:
      http:
        enabled: true
        receiverConfig: {}
      grpc:
        enabled: true
        receiverConfig: {}
  storage:
    trace:
      backend: s3
      s3:
        bucket: tempo-bucket
        endpoint: rook-ceph-rgw-ceph-objectstore.rook-ceph
        access_key: <path:homelab/data/aws-credentials/ceph/tempo-bucket#AWS_ACCESS_KEY_ID>
        secret_key: <path:homelab/data/aws-credentials/ceph/tempo-bucket#AWS_SECRET_ACCESS_KEY>
        insecure: true
  memcached:
    enabled: true
    replicas: 1
  memcachedExporter:
    enabled: true
  metaMonitoring:
    serviceMonitor:
      enabled: true
    grafanaAgent:
      enabled: false
  prometheusRule:
    enabled: true
  minio:
    enabled: false
  gateway:
    enabled: true
    replicas: 3
