---
argo-cd:
  controller:
    name: application-controller
    image:
      repository: ghcr.io/argoproj/argocd
      tag: 2.5.0-158e92c7
    replicas: 1
    args:
      appResyncPeriod: '60'
    metrics: &metrics
      enabled: true
      serviceMonitor:
        enabled: true

  dex:
    enabled: true
    metrics: *metrics

  redis:
    enabled: true
    metrics: *metrics

  server:
    enabled: true
    image:
      repository: ghcr.io/argoproj/argocd
      tag: 2.5.0-158e92c7
    metrics: *metrics
    ingress:
      enabled: true
      annotations:
        nginx.ingress.kubernetes.io/backend-protocol: HTTPS
        cert-manager.io/cluster-issuer: letsencrypt-prod
      ingressClassName: nginx
      paths:
        - /
      hosts:
        - &host argocd.homelab.linhng98.com
      tls:
        - secretName: argocd-tls
          hosts:
            - *host
      https: true

  repoServer:
    enabled: true
    metrics: *metrics

  applicationSet:
    enabled: true
    metrics: *metrics
