---
argo-cd:
  controller:
    name: application-controller
    replicas: 1

    args:
      appResyncPeriod: '60'
    metrics: &metrics
      enabled: true
      serviceMonitor:
        enabled: true

  dex:
    enabled: true
    metrics: *metrics

  redis:
    enabled: true
    metrics: *metrics

  server:
    enabled: true
    metrics: *metrics
    ingress:
      enabled: true
      annotations: {}
      labels: {}
      ingressClassName: nginx
      paths:
        - /
      hosts:
        - argocd.homelab.linhng98.com

  repoServer:
    enabled: true
    metrics: *metrics

  applicationSet:
    enabled: true
    metrics: *metrics
