---
argo-cd:
  controller:
    name: application-controller
    image:
      repository: ghcr.io/argoproj/argocd
      tag: 2.5.0-158e92c7
    replicas: 1
    args:
      appResyncPeriod: '60'
    metrics: &metrics
      enabled: true
      serviceMonitor:
        enabled: true

  dex:
    enabled: true
    metrics: *metrics

  redis:
    enabled: true
    metrics: *metrics

  server:
    enabled: true
    image:
      repository: ghcr.io/argoproj/argocd
      tag: 2.5.0-158e92c7
    metrics: *metrics
    ingress:
      enabled: true
      annotations:
        nginx.ingress.kubernetes.io/backend-protocol: HTTPS
        cert-manager.io/cluster-issuer: letsencrypt-prod
      ingressClassName: nginx
      paths:
        - /
      hosts:
        - &host argocd.homelab.linhng98.com
      tls:
        - secretName: argocd-tls
          hosts:
            - *host
      https: true

  repoServer:
    enabled: true
    metrics: *metrics
    volumes:
      - configMap:
          name: cmp-plugin
        name: cmp-plugin
      - name: custom-tools
        emptyDir: {}
    initContainers:
      - name: download-tools
        image: registry.access.redhat.com/ubi8
        env:
          - name: AVP_VERSION
            value: 1.11.0
          - name: HELM_VERSION
            value: v3.9.4
          - name: KUSTOMIZE_VERSION
            value: v4.5.7
        command: [sh, -c]
        args:
          - >-
            curl -L https://github.com/argoproj-labs/argocd-vault-plugin/releases/download/v$(AVP_VERSION)/argocd-vault-plugin_$(AVP_VERSION)_linux_amd64
            -o argocd-vault-plugin &&
            chmod +x argocd-vault-plugin &&
            mv argocd-vault-plugin /custom-tools/ && echo "installing helm" &&
            curl -L "https://get.helm.sh/helm-${HELM_VERSION}-linux-amd64.tar.gz" --output helm.tar.gz &&
            tar -zxvf helm.tar.gz &&
            cp linux-amd64/helm /custom-tools/helm && echo "installing kustomize" &&
            curl -LO "https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2F${KUSTOMIZE_VERSION}/kustomize_${KUSTOMIZE_VERSION}_linux_amd64.tar.gz"
            &&
            tar -zxvf kustomize_${KUSTOMIZE_VERSION}_linux_amd64.tar.gz &&
            mv kustomize /custom-tools

        volumeMounts:
          - mountPath: /custom-tools
            name: custom-tools
    envFrom:
      - secretRef:
          name: argocd-vault-plugin-credential
    extraContainers:
      - name: avp-helm
        command: [/var/run/argocd/argocd-cmp-server]
        image: registry.access.redhat.com/ubi8
        securityContext:
          runAsNonRoot: true
          runAsUser: 999
        volumeMounts:
          - mountPath: /var/run/argocd
            name: var-files
          - mountPath: /home/argocd/cmp-server/plugins
            name: plugins
          - mountPath: /tmp
            name: tmp-dir

          # Register plugins into sidecar
          - mountPath: /home/argocd/cmp-server/config/plugin.yaml
            subPath: avp-helm.yaml
            name: cmp-plugin

          # Important: Mount tools into $PATH
          - name: custom-tools
            subPath: argocd-vault-plugin
            mountPath: /usr/local/bin/argocd-vault-plugin
      - name: avp-kustomize
        command: [/var/run/argocd/argocd-cmp-server]
        image: registry.access.redhat.com/ubi8
        securityContext:
          runAsNonRoot: true
          runAsUser: 999
        volumeMounts:
          - mountPath: /var/run/argocd
            name: var-files
          - mountPath: /home/argocd/cmp-server/plugins
            name: plugins
          - mountPath: /tmp
            name: tmp-dir

          # Register plugins into sidecar
          - mountPath: /home/argocd/cmp-server/config/plugin.yaml
            subPath: avp-kustomize.yaml
            name: cmp-plugin

          # Important: Mount tools into $PATH
          - name: custom-tools
            subPath: argocd-vault-plugin
            mountPath: /usr/local/bin/argocd-vault-plugin
          - name: custom-tools
            subPath: helm
            mountPath: /usr/local/bin/helm
          - name: custom-tools
            subPath: kustomize
            mountPath: /usr/local/bin/kustomize

  applicationSet:
    enabled: true
    metrics: *metrics
