{{- range $path, $_ :=  .Files.Glob  "ruler/**.yaml" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $path | base }}
  annotations:
    k8s-sidecar-target-directory: /data-rules/homelab
  labels:
    mimir_rules: "1"
data:
{{ ($.Files.Glob $path).AsConfig | indent 2 }}
---
{{- end }}
