apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: watch-cm
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: watch-cm
subjects:
- kind: ServiceAccount
  name: mimir
  apiGroup: ""
- kind: ServiceAccount
  name: default
  apiGroup: ""
roleRef:
  kind: Role
  name: watch-cm
  apiGroup: rbac.authorization.k8s.io
