---
harbor:
  expose:
    type: ingress
    tls:
      enabled: true
      certSource: secret
      secret:
        secretName: harbor-core-tls
        notarySecretName: harbor-notary-tls
    ingress:
      hosts:
        core: harbor.homelab.linhng98.com
        notary: notary.homelab.linhng98.com
      controller: default
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt-prod
        ingress.kubernetes.io/ssl-redirect: 'true'
        ingress.kubernetes.io/proxy-body-size: '0'
        nginx.ingress.kubernetes.io/ssl-redirect: 'true'
        nginx.ingress.kubernetes.io/proxy-body-size: '0'
  externalURL: https://harbor.homelab.linhng98.com
  caSecretName: harbor-core-tls
  secretKey: <path:homelab/data/secrets/harbor#secretkey>
  updateStrategy:
    type: Recreate

  persistence:
    enabled: true
    persistentVolumeClaim:
      registry:
        size: 15Gi
      chartmuseum:
        size: 2Gi
    imageChartStorage:
      type: filesystem
      filesystem:
        rootdirectory: /storage

  harborAdminPassword: <path:homelab/data/secrets/harbor#password>

  portal:
    replicas: 1
    resources:
      requests:
        memory: 60Mi
        cpu: 10m

  chartmuseum:
    enabled: false

  jobservice:
    resources:
      requests:
        memory: 60Mi
        cpu: 10m

  core:
    replicas: 1
    resources:
      requests:
        memory: 60Mi
        cpu: 10m

  trivy:
    enabled: true
    resources:
      requests:
        memory: 60Mi
        cpu: 10m

  notary:
    enabled: true
    resources:
      requests:
        memory: 60Mi
        cpu: 10m

  metrics:
    enabled: true
    serviceMonitor:
      enabled: true

  exporter:
    resources:
      requests:
        memory: 60Mi
        cpu: 10m

  redis:
    resources:
      requests:
        memory: 60Mi
        cpu: 10m

  database:
    resources:
      requests:
        memory: 60Mi
        cpu: 10m
