---
apiVersion: v2
name: observability
version: 0.0.0
dependencies:
  - name: loki-stack
    version: 2.8.2
    repository: https://grafana.github.io/helm-charts
  - name: kube-prometheus-stack
    version: 40.0.2
    repository: https://prometheus-community.github.io/helm-charts
  - name: grafana
    version: 6.23.0
    repository: https://grafana.github.io/helm-charts
  - name: metrics-server
    version: 3.8.2
    repository: https://kubernetes-sigs.github.io/metrics-server
