---
loki-stack:
  loki:
    enabled: true
    isDefault: true
    serviceMonitor:
      enabled: true
  promtail:
    enabled: true
    config:
      logLevel: info
      serverPort: 3101
      clients:
        - url: http://{{ .Release.Name }}-loki:3100/loki/api/v1/push
    serviceMonitor:
      enabled: true

metrics-server:
  metrics:
    enabled: true

  serviceMonitor:
    enabled: true

kube-prometheus-stack:
  grafana:
    enabled: false

  prometheusOperator:
    prometheusConfigReloader:
      resources:
        requests:
          cpu: 10m
          memory: 50Mi

  prometheus:
    prometheusSpec:
      ruleSelectorNilUsesHelmValues: false
      serviceMonitorSelectorNilUsesHelmValues: false
      podMonitorSelectorNilUsesHelmValues: false
      probeSelectorNilUsesHelmValues: false

      externalLabels:
        cluster: homelab
      retention: 1d
      shards: 3
      storageSpec:
        volumeClaimTemplate:
          spec:
            accessModes: [ReadWriteOnce]
            resources:
              requests:
                storage: 5Gi

grafana:
  serviceMonitor:
    enabled: true

  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - &host grafana.homelab.linhng98.com
    tls:
      - secretName: grafana-tls
        hosts:
          - *host
  deploymentStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1

  admin:
    existingSecret: grafana-admin-dashboard
    userKey: admin-user
    passwordKey: admin-password

  persistence:
    enabled: false
  plugins:
    - vonage-status-panel
    - grafana-piechart-panel

  sidecar:
    enableUniqueFilenames: false
    dashboards:
      enabled: true
      provider:
        # disableDelete to activate a import-only behaviour
        disableDelete: true
        # allow updating provisioned dashboards from the UI
        allowUiUpdates: false
        # allow Grafana to replicate dashboard structure from filesystem
        foldersFromFilesStructure: true
    datasources:
      enabled: true
      defaultDatasourceEnabled: false

  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Loki
          type: loki
          url: http://observability-loki:3100

  grafana.ini:
    server:
      root_url: https://grafana.homelab.linhng98.com
    auth:
      disable_login_form: false
