---
loki-stack:
  loki:
    enabled: true
    isDefault: false
    config:
      auth_enabled: false
      ruler:
        storage:
          type: local
          local:
            directory: &rule_path /loki-rules
        rule_path: *rule_path
        alertmanager_url: http://observability-prom-alertmanager:9093
        ring:
          kvstore:
            store: inmemory
        enable_api: true
    extraContainers:
      - name: config-reloader
        image: docker.io/kiwigrid/k8s-sidecar:1.19.5
        env:
          - name: LABEL
            value: mimir_rules
          - name: UNIQUE_FILENAMES
            value: 'true'
          - name: FOLDER
            value: *rule_path
          - name: NAMESPACE
            value: mimir
          - name: RESOURCE
            value: configmap
          - name: FOLDER_ANNOTATION
            value: k8s-sidecar-target-directory
          - name: METHOD
            value: SLEEP
          - name: SLEEP_TIME
            value: '60'
        volumeMounts:
          - name: ruler-cm
            mountPath: *rule_path
    extraVolumes:
      - name: ruler-cm
        emptyDir: {}
    extraVolumeMounts:
      - name: ruler-cm
        mountPath: *rule_path
    serviceMonitor:
      enabled: true
  promtail:
    enabled: true
    config:
      logLevel: info
      serverPort: 3101
      clients:
        - url: http://{{ .Release.Name }}-loki:3100/loki/api/v1/push
    serviceMonitor:
      enabled: true

metrics-server:
  metrics:
    enabled: true

  serviceMonitor:
    enabled: true

prom:
  grafana:
    enabled: false

  prometheusOperator:
    prometheusConfigReloader:
      resources:
        requests:
          cpu: 10m
          memory: 50Mi

  prometheus:
    prometheusSpec:
      ruleSelectorNilUsesHelmValues: false
      serviceMonitorSelectorNilUsesHelmValues: false
      podMonitorSelectorNilUsesHelmValues: false
      probeSelectorNilUsesHelmValues: false

      externalLabels:
        cluster: homelab
      retention: 1d
      shards: 3
      storageSpec:
        volumeClaimTemplate:
          spec:
            accessModes: [ReadWriteOnce]
            resources:
              requests:
                storage: 5Gi
      remoteWrite:
        - url: http://mimir-nginx.mimir/api/v1/push
          headers:
            X-Scope-OrgID: homelab

grafana:
  serviceMonitor:
    enabled: true

  ingress:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
    hosts:
      - &host grafana.homelab.linhng98.com
    tls:
      - secretName: grafana-tls
        hosts:
          - *host
  deploymentStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1

  admin:
    existingSecret: grafana-admin-dashboard
    userKey: admin-user
    passwordKey: admin-password

  persistence:
    enabled: false
  plugins:
    - vonage-status-panel
    - grafana-piechart-panel

  sidecar:
    enableUniqueFilenames: false
    dashboards:
      enabled: true
      provider:
        # disableDelete to activate a import-only behaviour
        disableDelete: true
        # allow updating provisioned dashboards from the UI
        allowUiUpdates: false
        # allow Grafana to replicate dashboard structure from filesystem
        foldersFromFilesStructure: true
    datasources:
      enabled: true
      defaultDatasourceEnabled: false

  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: Loki
          type: loki
          url: http://observability-loki:3100
        - name: Prometheus
          isDefault: true
          type: prometheus
          url: http://mimir-nginx.mimir/prometheus
          basicAuth: false
          jsonData:
            httpHeaderName1: X-Scope-OrgID
          secureJsonData:
            httpHeaderValue1: homelab

  grafana.ini:
    server:
      root_url: https://grafana.homelab.linhng98.com
    auth:
      disable_login_form: false
    auth.google:
      enabled: true
      client_id: <path:homelab/data/google_oauth2/grafana#client_id>
      client_secret: <path:homelab/data/google_oauth2/grafana#client_secret>
      scopes: https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/userinfo.email
      auth_url: https://accounts.google.com/o/oauth2/auth
      token_url: https://accounts.google.com/o/oauth2/token
      allow_sign_up: true
