apiVersion: v1
kind: Secret
metadata:
  name: aws-credential
type: Opaque
data:
  AWS_ACCESS_KEY_ID: <path:homelab/data/aws-credentials/terragrunt#AWS_ACCESS_KEY_ID | base64encode>
  AWS_SECRET_ACCESS_KEY: <path:homelab/data/aws-credentials/terragrunt#AWS_ACCESS_KEY_ID | base64encode>
