---
base:
  global:
    istioNamespace: istio-system

istiod:
  pilot:
    resources:
      requests:
        cpu: 100m
        memory: 50Mi
  global:
    proxy:
      resources:
        requests:
          cpu: 10m
          memory: 128Mi
        limits:
          cpu: 200m
          memory: 500Mi

gateway:
  name: istio-ingressgateway
  replicaCount: 1
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 100m
      memory: 1024Mi

kiali-operator:
  cr:
    create: true
    spec:
      deployment:
        accessible_namespaces:
          - '**'
      auth:
        strategy: anonymous
      server:
        web_root: /
      external_services:
        prometheus:
          url: http://mimir-nginx.mimir/prometheus
          custom_headers:
            X-Scope-OrgID: homelab
