---
base:
  global:
    istioNamespace: istio-system

istiod:
  pilot:
    resources:
      requests:
        cpu: 100m
        memory: 50Mi
  global:
    proxy:
      resources:
        requests:
          cpu: 10m
          memory: 128Mi
        limits:
          cpu: 200m
          memory: 500Mi

gateway:
  replicaCount: 1
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 100m
      memory: 1024Mi

kiali-operator:
  cr:
    create: true
    spec:
      deployment:
        accessible_namespaces:
          - '**'
      #  ingress:
      #    class_name: nginx
      #    enabled: true
      #    override_yaml:
      #      metadata:
      #        annotations:
      #          cert-manager.io/cluster-issuer: letsencrypt-prod
      #      spec:
      #        rules:
      #          - http:
      #              paths:
      #                - path: /kiali
      #                  pathType: Prefix
      #                  backend:
      #                    serviceName: kiali
      #                    servicePort: 20001
      server:
        web_root: /
