---
base:
  global:
    istioNamespace: istio-system

istiod:
  pilot:
    resources:
      requests:
        cpu: 100m
        memory: 50Mi
  global:
    proxy:
      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          cpu: 200m
          memory: 500Mi

gateway:
  replicaCount: 1
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 100m
      memory: 1024Mi

kiali-server:
  auth:
    strategy: anonymous
  deployment:
    ingress:
      additional_labels:
        cert-manager.io/cluster-issuer: letsencrypt-prod
      class_name: nginx
      enabled: 'true'
  server:
    web_fqdn: kiali.homelab.linhng98.com
