---
base:
  global:
    istioNamespace: istio-system

istiod:
  pilot:
    resources:
      requests:
        cpu: 10m
        memory: 50Mi
  global:
    proxy:
      resources:
        requests:
          cpu: 10m
          memory: 128Mi
        limits:
          cpu: 50m
          memory: 500Mi

gateway:
  replicaCount: 1
  resources:
    requests:
      cpu: 10m
      memory: 128Mi
    limits:
      cpu: 100m
      memory: 1024Mi
