---
name: build and release new version document
run-name: ${{ github.actor }} release new document version
on:
  push:
    paths:
      - documents/**

jobs:
  build-push-document-container:
    runs-on: homelab
    env:
      CONTAINER: document
    steps:
      - uses: actions/checkout@v3
      - name: set env
        run: |
          echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-8)" >> $GITHUB_ENV
      - name: install aws cli
        run: curl -Lo skaffold https://storage.googleapis.com/skaffold/releases/latest/skaffold-linux-amd64 && sudo install skaffold /usr/local/bin/
      - name: install aws cli
        run: |
          sudo apt update -y
          sudo apt install -y unzip
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install
          aws --version
      - name: create compress tar
        run: |
          tar -C documents -zcvf context-${{ env.GITHUB_SHA_SHORT }}.tar.gz .
      - name: configure aws cli
        run: |
          export context_tgz=context-${{ env.GITHUB_SHA_SHORT }}.tar.gz
          cp /tmp/.aws/credentials ~/.aws/credentials
          aws s3 cp ${context_tgz} s3://mess-around-kaniko/${CONTAINER}/${context_tgz}
