---
name: pre-commit hook check
run-name: pre-commit hook check
on:
  pull_request:
  push:


jobs:
  pre-commit:
    runs-on: homelab
    container: ubuntu:22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - uses: pre-commit/action@v3.0.0
