apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: kibana-credentials
  namespace: elastic-cluster
spec:
  encryptedData:
    encryptionkey: AgBMmI+qlhpAExD7a3sskJ9dayac/MpR+vzCTHqOcsNB8JDlkYhRvEKCKOD+Sb/BAbNXzyU8VLb/Oy2fHRYKFK//4PA4icktbojZ2mK0+6B1a+wX5PaVLJg+IhNKr/iuS/K3Id3ENd6crpIMzJI8HlnzDiPRzu8412VYgUXOzX8/pPgp7u3MNKjxzZUL2eRY6lwv3cUdOmN+1JFd0e7LYRmb2Tb6JughzhqgRHx1yc2IqXUBrCm/GojaURijgHnuo+ni4eQYJ/KAM1QAPoZ2cfUK1WiU1WShf08gaSDdmefajokzxwfwoSp0qV/cWtiZdvActbPPtjEJl6mHb5YyArtztYsQsJ8yk8H2ZgUPXaMpgMwVcdYd7gfj3mu3WQOYWbmP5cjDYgOgSsqVRSxnQJPuS6wDVVFCOhB5i+enGXBUUCfvk7DaBoJdRl316Xke0Ciatea58vg7Xrujtzzvh/aIiTgW5LjFcnTqMVITCDOAFvKmk6UwXnSlcAWiUS5LBfS/0H+myvayupO2LMXIkXIcLj2e92gnMTnQucnM9pUt+mYlL8yqCRhE9Rldus1V32VXe0qT0hEkyUPfiwPxr7TmLOXkHGIQZ5OlmRhowG5GKwjjVpKb/C1Xhl1Y/HIdW9Q4g277Me89iUpTTP0OlQ5qKTZpTiwwyo0e23Db+p5OtSag5EItGG9M6lE1vDD00UBNF4Q3patqztQ4tJrK+hx7tmkqdMDcAhepJ5qedLL9VA==
